theme: jekyll-theme-slate
project_title: "MonkeyPod: PHP SDK"
avatar: "https://monkeypod.io/images/logo-horizontal.png"
round-avatar: false

navbar-links:
  MonkeyPod: "https://monkeypod.io"
  SDK: 
    Intro: "index"
